---

- name: Install flatpak
  ansible.builtin.package:
    name: flatpak
    state: present

- name: Add the flathub flatpak repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Include flathub packages from config.
  set_fact:
    flathubpackages: "{{ flathubpackages + Config.flathubpackages }}"
  when: Config.flathubpackages is defined

- name: Install flathub packages
  flatpak:
    name: "{{ flathubpackages }}"
    state: present
