---
# tasks file for InstallUbuntuDesktop
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/subelements_lookup.html
#https://groups.google.com/g/ansible-project/c/8XJkHQgttLA

- name: Install software using package (This can take a wile..)
  ansible.builtin.package:
    name: "{{ desktoppackages }}"
    state: present

- name: Add users
  include_tasks: users.yml

- name: Set wallpapers and avatars
  include_tasks: themes.yml

- name: Install Sanoid
  include_tasks: sanoid.yml

- name: Install snaps
  include_tasks: snaps.yml

- name: Install flatpak
  include_tasks: flatpak.yml

- name: Install tailscale
  include_tasks: tailscale.yml

- name: Install Brave browser
  include_tasks: tailscale.yml