---
# tasks file for InstallUbuntuDesktop


- name: Install software using package (This can take a wile..)
  ansible.builtin.package:
    name: "{{ desktoppackages }}"
    state: present

- name: Add users
  include_tasks: users.yml

- name: Apply System Settings
  include_tasks: themes.yml

- name: Apply User Settings
  include_tasks: user-settings.yml
  loop: "{{ Users }}"

- name: Install Sanoid
  include_tasks: sanoid.yml

#Installing snaps in chroot doesn't work...
#- name: Install snaps
#  include_tasks: snaps.yml

- name: Install flatpak
  include_tasks: flatpak.yml

- name: Install tailscale
  include_tasks: tailscale.yml

- name: Install Brave browser
  include_tasks: brave.yml

# Need a post chroot task to fix brave on first boot.
  #sudo apt-get --reinstall install brave-browser