---

# Fix snaps
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /usr/lib/systemd/system/snapd.mounts-pre.target
    dest: /etc/systemd/system/snapd.mounts-pre.target
    owner: root
    group: root
    mode: '0644'

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /usr/lib/systemd/system/snapd.mounts.target
    dest: /etc/systemd/system/snapd.mounts.target
    owner: root
    group: root
    mode: '0644'

# Install snaps
- name: Install snaps
  community.general.snap:
    name: "{{ snappackages }}"
