---
- name: Tailscale Dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ tailscale_apt_dependencies }}"
    cache_valid_time: 3600
    state: present

- name: Add Tailscale Signing Key
  become: true
  ansible.builtin.get_url:
    url: "{{ tailscale_apt_signkey }}"
    dest: "{{ tailscale_apt_keyring_path }}"
    mode: '0644'

- name: Add Tailscale Repo
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ tailscale_apt_deb }}"
    state: present

- name: Install Tailscale
  become: true
  ansible.builtin.apt:
    name: tailscale
    cache_valid_time: 3600
    state: present
