



- name: Install software using package (This can take a wile..)
  ansible.builtin.package:
    name: "{{ gdm3editpackages }}"
    state: present

#Script from https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background
- name: Change GDM3 background
  ansible.builtin.shell:
    cmd: files/ubuntu-gdm-set-background --image /usr/share/backgrounds/DSC2943_by_kcpru.jpg