---

#Set GDM3 background
- name: Install GDM edit dependencies
  ansible.builtin.package:
    name: "{{ gdm3editpackages }}"
    state: present

- name: Download GDM3 Wallpaper
  ansible.builtin.get_url:
    url: "{{ Config.gdm3wallpaper }}"
    dest: "/usr/share/backgrounds/UDZFS"
    mode: '0644'

  #Script from https://github.com/PRATAP-KUMAR/ubuntu-gdm-set-background
- name: Change GDM3 background
  ansible.builtin.script:
    cmd: ubuntu-gdm-set-background --image /usr/share/backgrounds/UDZFS

#Create avatars

- name: Download avatar
  ansible.builtin.get_url:
    url: "{{ item.avatar }}"
    dest: "/var/lib/AccountsService/icons/{{ item.username }}"
    mode: '0644'
    owner: "{{ item.username }}"
  loop: "{{ Users | selectattr('avatar', 'defined') }}"


- name: Template AccountsService User
  ansible.builtin.template:
    src: templates/ASUser.j2
    dest: "/var/lib/AccountsService/users/{{ item.username }}"
    owner: "{{ item.username }}"
    mode: '0444'
  loop: "{{ Users | selectattr('avatar', 'defined') }}"

#Set wallpaper

- name: Install dconf edit dependencies
  ansible.builtin.package:
    name: "{{ dconfpackages }}"
    state: present

- name: Download Wallpapers
  ansible.builtin.get_url:
    url: "{{ item.wallpaper }}"
    dest: "/home/{{ item.username }}/.wallpaper"
    mode: '0644'
    owner: "{{ item.username }}"
  loop: "{{ Users | selectattr('wallpaper', 'defined') }}"

- name: Set GNOME Wallpaper
  become_user: "{{ item.username }}"
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ item.username }}/.wallpaper'"
  loop: "{{ Users | selectattr('wallpaper', 'defined') }}"

- name: Set GNOME Wallpaper scale
  become_user: "{{ item.username }}"
  dconf: key="/org/gnome/desktop/background/picture-options" value="'scaled'"
  loop: "{{ Users | selectattr('wallpaper', 'defined') }}"
