---
# vars file for InstallUbuntuDesktop
desktoppackages:
  - ubuntu-desktop-minimal
  - git
  - socat
  - nano

gdm3editpackages:
  - libglib2.0-dev-bin

sanoidpackages:
  - debhelper 
  - libcapture-tiny-perl 
  - libconfig-inifiles-perl 
  - pv 
  - lzop 
  - mbuffer 
  - build-essential

dconfpackages:
  - python3-psutil

# Packages not to be installed
holdpackages:
  - grub-pc
  - grub-pc-bin
  - os-prober


flathubpackages:
  - org.libreoffice.LibreOffice
  - org.videolan.VLC

snappackages:
  - firefox

tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg
tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }} {{ ansible_distribution_release | lower }} main
tailscale_apt_signkey: https://pkgs.tailscale.com/{{ release_stability | lower }}/{{ tailscale_debian_distro[ansible_distribution | lower] }}/{{ ansible_distribution_release | lower }}.noarmor.gpg

tailscale_apt_dependencies:
  - gnupg2
  - gnupg-agent
  - apt-transport-https
  - python3-apt