---
# vars file for InstallUbuntuDesktop
desktoppackages:
  - ubuntu-desktop-minimal
  - git
  - socat
  - dnsutils
  - terminator
  - net-tools
  - telnet

gdm3editpackages:
  - libglib2.0-dev-bin

sanoidpackages:
  - debhelper
  - libcapture-tiny-perl
  - libconfig-inifiles-perl
  - pv
  - lzop
  - mbuffer
  - build-essential

dconfpackages:
  - python3-psutil

# Packages not to be installed
holdpackages:
  - grub-pc
  - grub-pc-bin
  - os-prober
  - sssd


flathubpackages:
  - org.mozilla.firefox
  - org.chromium.Chromium

snappackages:
  - firefox

tailscale_apt_keyring_path: /usr/share/keyrings/tailscale-archive-keyring.gpg
tailscale_apt_deb: deb [signed-by={{ tailscale_apt_keyring_path }}] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release | lower }} main
tailscale_apt_signkey: https://pkgs.tailscale.com/stable/ubuntu//{{ ansible_distribution_release | lower }}.noarmor.gpg

tailscale_apt_dependencies:
  - gnupg2
  - gnupg-agent
  - apt-transport-https
  - python3-apt
