---
- name: Add users
  hosts: localhost
  gather_facts: false
  vars:
   - baseuri: 192.168.33.147

  tasks:

   - name: Add the user 'johnd'
     ansible.builtin.user:
      name: johnd
      comment: John Doe
      uid: 1040

